apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x4n5vg1l2-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x4n5vg1l2-java-quarkus-gitops